name: Blacksmith
main: Blacksmith\Main
version: 1.0.0
api: 5.0.0
commands:
  blacksmith:
    description: Open the Blacksmith menu
    usage: "/blacksmith"
    permission: blacksmith.use
permissions:
  blacksmith.use:
    default: true
