name: Blacksmith
main: Blacksmith\Main
version: 1.0.0
api: 5.0.0
commands:
  blacksmith:
    description: Open the Blacksmith GUI
    usage: "/blacksmith"
    permission: blacksmith.use
    permission-message: "You do not have permission to use this command!"
